# Generated by Django 4.1.6 on 2023-02-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnir',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
