# Generated by Django 4.1.6 on 2023-02-08 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_rename_created_date_turnir_events_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnir',
            name='sportsmen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.sportsmen'),
        ),
    ]
