# Generated by Django 4.1.6 on 2023-02-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_turnir_sportsmen'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsmen',
            name='wins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
