# Generated by Django 4.1.6 on 2023-02-08 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_remove_turnir_sportsmen_sportsmen_turnir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsmen',
            name='turnir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_turnir', to='server.turnir'),
        ),
    ]
