# Generated by Django 4.1.6 on 2023-02-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_sportsmen_turnir'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsAchieveEvents',
            new_name='AchieveEventsImage',
        ),
        migrations.RemoveField(
            model_name='sportsmen',
            name='turnir',
        ),
        migrations.AddField(
            model_name='turnir',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
