# Generated by Django 4.1.6 on 2023-02-08 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_rename_newsachieveevents_achieveeventsimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='News', to='server.news'),
        ),
    ]
