# Generated by Django 4.1.6 on 2023-02-08 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_alter_newsimage_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achieveeventsimage',
            name='achieve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achieve_images', to='server.achieveevents'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_images', to='server.news'),
        ),
        migrations.AlterField(
            model_name='sportsmen',
            name='pol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sportsmen_pol', to='server.pol'),
        ),
    ]
