# Generated by Django 4.1.6 on 2023-02-08 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_alter_achieveeventsimage_achieve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsmen',
            name='weight_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_sportsmen', to='server.weightcategory'),
        ),
    ]
