# Generated by Django 4.1.6 on 2023-02-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_alter_sportsmen_pol_alter_sportsmen_weight_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='image',
            field=models.ImageField(default='', upload_to='coaches/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnir',
            name='image',
            field=models.ImageField(default='', upload_to='turnir/'),
            preserve_default=False,
        ),
    ]
