# Generated by Django 4.1.6 on 2023-02-09 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_coach_image_turnir_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='achieveevents',
            options={'verbose_name': 'Прошедшие турниры', 'verbose_name_plural': 'Прошедшие турниры'},
        ),
        migrations.CreateModel(
            name='ShopThing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='shop_things/')),
                ('price', models.FloatField()),
                ('size_s', models.BooleanField(default=True)),
                ('size_m', models.BooleanField(default=True)),
                ('size_l', models.BooleanField(default=True)),
                ('size_xl', models.BooleanField(default=True)),
                ('size_xxl', models.BooleanField(default=True)),
                ('size_xxxl', models.BooleanField(default=True)),
                ('shop_categoty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_things', to='server.shopcategory')),
            ],
        ),
    ]
